Public Class Jugador
    Public Property Indice As Integer
    Public Property Nombre As String
    Public Property Position As String
    Public Property Offense As Integer
    Public Property Defense As Integer
    Public Property BodyBalance As Integer
    Public Property Stamina As Integer
    Public Property Speed As Integer
    Public Property Acceleration As Integer
    Public Property PassAcc As Integer
    Public Property ShotPwr As Integer
    Public Property ShotAcc As Integer
    Public Property Jump As Integer
    Public Property Head As Integer
    Public Property Technique As Integer
    Public Property Dribble As Integer
    Public Property Curve As Integer
    Public Property Aggression As Integer
    Public Property Response As Integer
    Public Property Age As Integer
    Public Property Height As Integer
    Public Property Body As String
    Public Property SkinColor As String
    Public Property PlayerNumber As Integer
    Public Property Hair As String
    Public Property HairColor As String
    Public Property HairFace As String
    Public Property HairColorFace As String
    Public Property Feet As String
    Public Property Boots As String
    Public Property FeetOutside As String
    Public Property Team As String
    Public Property NatNumber As String
    Public Property Club As String
    Public Property ClubNumber As String
    Public Property Birthday As String
    Public Property Link As String
End Class
